// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: jobqueue/v1/jobqueue.proto

package jobqueuepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // raw JSON, opaque to this service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_jobqueue_v1_jobqueue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobqueue_v1_jobqueue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_jobqueue_v1_jobqueue_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubmitRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_jobqueue_v1_jobqueue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobqueue_v1_jobqueue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_jobqueue_v1_jobqueue_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_jobqueue_v1_jobqueue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobqueue_v1_jobqueue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_jobqueue_v1_jobqueue_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *StatusUpdate          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_jobqueue_v1_jobqueue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobqueue_v1_jobqueue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_jobqueue_v1_jobqueue_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetStatus() *StatusUpdate {
	if x != nil {
		return x.Status
	}
	return nil
}

type WatchStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchStatusRequest) Reset() {
	*x = WatchStatusRequest{}
	mi := &file_jobqueue_v1_jobqueue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStatusRequest) ProtoMessage() {}

func (x *WatchStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobqueue_v1_jobqueue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStatusRequest.ProtoReflect.Descriptor instead.
func (*WatchStatusRequest) Descriptor() ([]byte, []int) {
	return file_jobqueue_v1_jobqueue_proto_rawDescGZIP(), []int{4}
}

func (x *WatchStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Attempts      int32                  `protobuf:"varint,3,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,4,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	LastError     string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_jobqueue_v1_jobqueue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_jobqueue_v1_jobqueue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_jobqueue_v1_jobqueue_proto_rawDescGZIP(), []int{5}
}

func (x *StatusUpdate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatusUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusUpdate) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *StatusUpdate) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *StatusUpdate) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

var File_jobqueue_v1_jobqueue_proto protoreflect.FileDescriptor

const file_jobqueue_v1_jobqueue_proto_rawDesc = "" +
	"\n" +
	"\x1ajobqueue/v1/jobqueue.proto\x12\vjobqueue.v1\"=\n" +
	"\rSubmitRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\" \n" +
	"\x0eSubmitResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\"\n" +
	"\x10GetStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"F\n" +
	"\x11GetStatusResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.jobqueue.v1.StatusUpdateR\x06status\"$\n" +
	"\x12WatchStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x94\x01\n" +
	"\fStatusUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\battempts\x18\x03 \x01(\x05R\battempts\x12!\n" +
	"\fmax_attempts\x18\x04 \x01(\x05R\vmaxAttempts\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError2\xe6\x01\n" +
	"\bJobQueue\x12A\n" +
	"\x06Submit\x12\x1a.jobqueue.v1.SubmitRequest\x1a\x1b.jobqueue.v1.SubmitResponse\x12J\n" +
	"\tGetStatus\x12\x1d.jobqueue.v1.GetStatusRequest\x1a\x1e.jobqueue.v1.GetStatusResponse\x12K\n" +
	"\vWatchStatus\x12\x1f.jobqueue.v1.WatchStatusRequest\x1a\x19.jobqueue.v1.StatusUpdate0\x01BNZLgithub.com/Harshilagg/Observable_Job_Queue/internal/pb/jobqueuepb;jobqueuepbb\x06proto3"

var (
	file_jobqueue_v1_jobqueue_proto_rawDescOnce sync.Once
	file_jobqueue_v1_jobqueue_proto_rawDescData []byte
)

func file_jobqueue_v1_jobqueue_proto_rawDescGZIP() []byte {
	file_jobqueue_v1_jobqueue_proto_rawDescOnce.Do(func() {
		file_jobqueue_v1_jobqueue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobqueue_v1_jobqueue_proto_rawDesc), len(file_jobqueue_v1_jobqueue_proto_rawDesc)))
	})
	return file_jobqueue_v1_jobqueue_proto_rawDescData
}

var file_jobqueue_v1_jobqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_jobqueue_v1_jobqueue_proto_goTypes = []any{
	(*SubmitRequest)(nil),      // 0: jobqueue.v1.SubmitRequest
	(*SubmitResponse)(nil),     // 1: jobqueue.v1.SubmitResponse
	(*GetStatusRequest)(nil),   // 2: jobqueue.v1.GetStatusRequest
	(*GetStatusResponse)(nil),  // 3: jobqueue.v1.GetStatusResponse
	(*WatchStatusRequest)(nil), // 4: jobqueue.v1.WatchStatusRequest
	(*StatusUpdate)(nil),       // 5: jobqueue.v1.StatusUpdate
}
var file_jobqueue_v1_jobqueue_proto_depIdxs = []int32{
	5, // 0: jobqueue.v1.GetStatusResponse.status:type_name -> jobqueue.v1.StatusUpdate
	0, // 1: jobqueue.v1.JobQueue.Submit:input_type -> jobqueue.v1.SubmitRequest
	2, // 2: jobqueue.v1.JobQueue.GetStatus:input_type -> jobqueue.v1.GetStatusRequest
	4, // 3: jobqueue.v1.JobQueue.WatchStatus:input_type -> jobqueue.v1.WatchStatusRequest
	1, // 4: jobqueue.v1.JobQueue.Submit:output_type -> jobqueue.v1.SubmitResponse
	3, // 5: jobqueue.v1.JobQueue.GetStatus:output_type -> jobqueue.v1.GetStatusResponse
	5, // 6: jobqueue.v1.JobQueue.WatchStatus:output_type -> jobqueue.v1.StatusUpdate
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jobqueue_v1_jobqueue_proto_init() }
func file_jobqueue_v1_jobqueue_proto_init() {
	if File_jobqueue_v1_jobqueue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobqueue_v1_jobqueue_proto_rawDesc), len(file_jobqueue_v1_jobqueue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobqueue_v1_jobqueue_proto_goTypes,
		DependencyIndexes: file_jobqueue_v1_jobqueue_proto_depIdxs,
		MessageInfos:      file_jobqueue_v1_jobqueue_proto_msgTypes,
	}.Build()
	File_jobqueue_v1_jobqueue_proto = out.File
	file_jobqueue_v1_jobqueue_proto_goTypes = nil
	file_jobqueue_v1_jobqueue_proto_depIdxs = nil
}
