// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: jobqueue/v1/jobqueue.proto

package jobqueuepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobQueue_Submit_FullMethodName      = "/jobqueue.v1.JobQueue/Submit"
	JobQueue_GetStatus_FullMethodName   = "/jobqueue.v1.JobQueue/GetStatus"
	JobQueue_WatchStatus_FullMethodName = "/jobqueue.v1.JobQueue/WatchStatus"
)

// JobQueueClient is the client API for JobQueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JobQueue is the client-facing API for submitting jobs and observing
// their progress. It is a thin layer over the storage layer in
// internal/store — it never contains claim/execute/retry logic, which
// stays in internal/worker.
type JobQueueClient interface {
	// Submit enqueues a new job and returns its id immediately. It does
	// not wait for the job to run.
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	// GetStatus returns a job's state as of the moment of the call — a
	// single snapshot, not a subscription.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// WatchStatus streams status updates for one job until it reaches a
	// terminal state (completed or failed), at which point the server
	// closes the stream.
	WatchStatus(ctx context.Context, in *WatchStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusUpdate], error)
}

type jobQueueClient struct {
	cc grpc.ClientConnInterface
}

func NewJobQueueClient(cc grpc.ClientConnInterface) JobQueueClient {
	return &jobQueueClient{cc}
}

func (c *jobQueueClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, JobQueue_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobQueueClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, JobQueue_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobQueueClient) WatchStatus(ctx context.Context, in *WatchStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobQueue_ServiceDesc.Streams[0], JobQueue_WatchStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchStatusRequest, StatusUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobQueue_WatchStatusClient = grpc.ServerStreamingClient[StatusUpdate]

// JobQueueServer is the server API for JobQueue service.
// All implementations must embed UnimplementedJobQueueServer
// for forward compatibility.
//
// JobQueue is the client-facing API for submitting jobs and observing
// their progress. It is a thin layer over the storage layer in
// internal/store — it never contains claim/execute/retry logic, which
// stays in internal/worker.
type JobQueueServer interface {
	// Submit enqueues a new job and returns its id immediately. It does
	// not wait for the job to run.
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	// GetStatus returns a job's state as of the moment of the call — a
	// single snapshot, not a subscription.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// WatchStatus streams status updates for one job until it reaches a
	// terminal state (completed or failed), at which point the server
	// closes the stream.
	WatchStatus(*WatchStatusRequest, grpc.ServerStreamingServer[StatusUpdate]) error
	mustEmbedUnimplementedJobQueueServer()
}

// UnimplementedJobQueueServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobQueueServer struct{}

func (UnimplementedJobQueueServer) Submit(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedJobQueueServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedJobQueueServer) WatchStatus(*WatchStatusRequest, grpc.ServerStreamingServer[StatusUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchStatus not implemented")
}
func (UnimplementedJobQueueServer) mustEmbedUnimplementedJobQueueServer() {}
func (UnimplementedJobQueueServer) testEmbeddedByValue()                  {}

// UnsafeJobQueueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobQueueServer will
// result in compilation errors.
type UnsafeJobQueueServer interface {
	mustEmbedUnimplementedJobQueueServer()
}

func RegisterJobQueueServer(s grpc.ServiceRegistrar, srv JobQueueServer) {
	// If the following call panics, it indicates UnimplementedJobQueueServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobQueue_ServiceDesc, srv)
}

func _JobQueue_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobQueueServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobQueue_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobQueueServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobQueue_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobQueueServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobQueue_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobQueueServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobQueue_WatchStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobQueueServer).WatchStatus(m, &grpc.GenericServerStream[WatchStatusRequest, StatusUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobQueue_WatchStatusServer = grpc.ServerStreamingServer[StatusUpdate]

// JobQueue_ServiceDesc is the grpc.ServiceDesc for JobQueue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobQueue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobqueue.v1.JobQueue",
	HandlerType: (*JobQueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _JobQueue_Submit_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _JobQueue_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStatus",
			Handler:       _JobQueue_WatchStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jobqueue/v1/jobqueue.proto",
}
